name: 云测试

on: [pull_request,push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: 构建 Python 环境 ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: 使用 Pylint 检查代码拼写
      run: |
        pylint $(git ls-files '*.py') --disable=missing-module-docstring,wildcard-import,invalid-name,W0614,missing-module-docstring,too-few-public-methods,too-many-locals,undefined-variable,import-error,no-name-in-module,missing-function-docstring,wrong-import-order,unused-import,non-ascii-name,bare-except,wrong-import-position,too-many-statements,too-many-branches,unused-variable,unsupported-binary-operation,unnecessary-pass,too-many-return-statements,unnecessary-lambda-assignment,missing-class-docstring,no-member,line-too-long,import-outside-toplevel,multiple-statements,ungrouped-imports,redefined-outer-name,R0801,unused-argument,too-many-arguments,relative-beyond-top-level,function-redefined,redefined-builtin,trailing-whitespace,cyclic-import,cyclic-import,W0719,no-value-for-parameter,not-callable,W0012
    - name: 运行测试集
      run: /
        python run_test.py
